### ISSUE TITLE
"Cannot find namespace 'JSX'." in basic Nuxt Project

### ISSUE THREAD

**Issue by FoxyHutch** [Maronato/vue-toastification#102]
First of all, I really enjoy working with your library, Great job!
I switched from a "normal" vue-cli-project to nuxt, and encountered the following error.

## Versions
1.7.6

## Describe the bug
When setting up a project with nuxt `$ yarn create nuxt-app <project-name>` with Typescript and following your guide for nuxt (add module to nuxt.config and add types), i get the following errors in the server console (terminal) on startup of the dev server:

<img width="1105" alt="grafik" src="https://user-images.githubusercontent.com/16386365/84168293-85bfef80-aa77-11ea-974f-2bd6e76eae6a.png">

Despite the error the server is starting up and the webapp and the toasts work without any browser console errors.

## Expected behavior
Starting up the dev server without any errors

## Steps to reproduce
1. Install with nuxt `$ yarn create nuxt-app <project-name>` and use following parameters:
  - Typescript
  - Yarn
  - UI Framework: None
  - Custom Server: None
  - Runtime for TS: Default
  - No Nuxt modules
  - Linting Tools: ESLint, Prettier
  - Test Framework: None
  - Rendering Mode: Universal
2. `yarn add vue-toastification`
3. Add `"vue-toastification/nuxt"` to nuxt.config without further options
4. Add `"vue-toastification/nuxt"` to tsconfig
5. Add some sample Toast-Button for showing a toast in index.vue
6. Startup dev server with `yarn dev`

## Your Environment
 - Device: Macbook Pro early 2013
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 1.7.6
 - Node: 14.4

**Comment by FoxyHutch** [comment]
oh, I just saw you already helped someone with the same issue (#67).
Adding a shims-tsx.d.ts as described works perfectly.

**Comment by Maronato** [comment]
Glad you found it :)
