### ISSUE TITLE
Saving History of Notifications

### ISSUE THREAD

**Issue by kiran94** [Maronato/vue-toastification#105]
Firstly thank you for providing such an awesome library!

This request is basically adding the ability to save all messages sent through `this.$toast` into an additional store so we can essentially have a notification history for everything sent into the library. 

## Detailed Description
I'm not sure if it's possible and I've missed an option but I think it would be handy if the library could provide an option to additionally redirect submitted messages to *something else* e.g a state variable in a Vuex store. 

This is a common pattern in popular applications like Facebook or Youtube where notifications will be sent and then there will be a little icon somewhere where you can view previous notification. 

I'm not really sure if it's something you think is within scope for this library. Additionally, users could have a quick workaround where they submit to their store of choice + call this library in 2 lines but I feel this is quite a unmaintainable solution or less clean solution as you need to duplicate this everywhere you call `this.$toast` if that makes sense. 

## Context
Important so that we can provide users with a history of all the notifications that have appeared in the application. As notifications eventually disappear after a few seconds, this could be quite useful and meets a common pattern I've described above. 

Just in case it makes a difference, I am using Nuxt. 

## Possible Implementation
I'm not confident enough on this library to comment on specific implementation details but you could configure this upfront where when you are initialising the library, you also provide something like a `callback` option that is provided with an object. This object would have details like `content` and `TYPE` and anything else you feel would be useful. Such a callback could be called [here](https://github.com/Maronato/vue-toastification/blob/96c6a5f4e630a5ad1fe9cdbad15aa8ef308a9a00/src/ts/interface.ts#L40) but I'm not sure if this is the best place to put it.

**Comment by Maronato** [comment]
Hello! I'm glad you like the plugin :)

You can already do something like that using [toast filters](https://github.com/Maronato/vue-toastification#custom-toast-filters). They allow you to modify toasts before they are created and may be used to save created toasts automatically.

Here is an example showing how that would work:

![CleanShot 2020-07-01 at 12 15 04](https://user-images.githubusercontent.com/19658460/86261165-96eeae80-bb94-11ea-8b63-0663d9263a15.gif)


And the code is available here:

[![Edit xenodochial-archimedes-zcr4h](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-archimedes-zcr4h?fontsize=14&hidenavigation=1&theme=dark)

If you feel like the solution is not enough, feel free to reopen the issue and we can discuss other implementations.
