### ISSUE TITLE
Chrome throws `[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.` in the console.

### ISSUE THREAD

**Issue by bhaskar-nair2** [Maronato/vue-toastification#117]
## Versions

- 1.0 (1.7.6)

## Describe the bug

Whnever a toast pops-up Chrome's console throws a Warning like so:

`json
index.js?6c42:998 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
`

This is the file:line responsible for the warning
`webpack:///./node_modules/vue-toastification/dist/esm/index.js?6c42`

## Expected behavior

There should be no warning thrown

## Steps to reproduce

The warning is not thrown in CodeSandbox as this seems to be Browser Specific
Steps:
1. Install normally
2. Set up plugin
3. Using chrome, show a toast
4. Warning for the same pops up

## Your Environment

 - Device: PC
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 84.04 (Stable)

**Comment by Maronato** [comment]
Hello! Thanks for reporting this and sorry it took so long to fix. It'll go live soon on `v1.7.8`
