### ISSUE TITLE
Content Defaults

### ISSUE THREAD

**Issue by jd-0001** [Maronato/vue-toastification#135]
Hi, I am really impressed by the way it provides flexibility. :heart: 

One thing I would like to know is is it possible to provide a default for content because I am using a custom Vue component as content and providing a message as a prop of that component.

## Detailed Description
Is it possible to provide content defaults just like toast option default. Please consider below example without this feature:
```js
    toast(
      {
        component: NotificationContent,
        position: 'bottom-right',
        props: {
          title: 'Event Updated',
          icon: 'CheckIcon',
          variant: 'success',
        },
      },
      {
        timeout: 3000,
      },
    )
```

Now next time if I want to show success toast every time I have to write the same with just change in `title` prop.

## Context

If we can provide content default for custom components somehow it will be really easy to use.

**How would you use it?**
I think passing just uncommon props will be better and providing.

## Possible Implementation
I didn't dive into your plugin yet, so no comments. But can be the same as options I guess.

Again I realy liked this flexibility of using custom component :+1:

**Comment by Maronato** [comment]
Hello! I'm glad you like the plugin :)

I think that setting default content for toasts is a little more complex than setting default options. When you define a default options object, all that is needed is to merge two simple flat objects. With content, there is *string* content vs *component content* vs *JSX* content.
Going deeper, how do you merge the props? Vue Toastification makes no assumption about the shape of the props and listeners, so merging them would maybe require users to provide reduce functions, etc.

What most people do to circumvent this is to wrap the plugin in a mixin that exposes a function that only takes the `title` as the parameter:

```js
export default {
  methods: {
    successToast(title) {
      this.$toast.success({
        component: NotificationContent,
        props: {
          title,
          icon: 'CheckIcon',
          variant: 'success',
        },
      },
      {
        position: 'bottom-right',
        timeout: 3000,
      })
    },
  },
}
```

**Comment by jd-0001** [comment]
Hi, @Maronato 

Thanks for your efforts and time :+1: 

I will try to find mixin kind of solutions.

Regards.
