### ISSUE TITLE
CSS not imported in production build

### ISSUE THREAD

**Issue by s001dxp** [Maronato/vue-toastification#136]
## Versions
- 2.0

## Describe the bug
The css is not included in the production build. It is, however, included for development builds.

## Expected behavior
I expect the CSS to be in the compiled css after building for production.

## Steps to reproduce
1.) include the vue-toastification in a vue project.
2.) Execute a production build.

**Comment by 7FyOh** [comment]
I am encountering the same problem. @s001dxp How have you solved it?

**Comment by s001dxp** [comment]
In our case we had to white list  Vue-Toastification in the postcss.config.js file.

**Comment by 7FyOh** [comment]
Thanks, that solved my problem as well.
