### ISSUE TITLE
Any way to update an existing notification?

### ISSUE THREAD

**Issue by trevorgehman** [Maronato/vue-toastification#14]
Let's say we have a toast notification that shows "Loading..." but instead of just dismissing it at some point, we want to update the notification to show "Loaded! Click here" when it's ready.

Is there a way to accomplish this? I know we can save the toast ID and use that to dismiss it at a later point, but can we also update the content?

**Comment by trevorgehman** [comment]
I love the fact that I can create a component and use that for a notification. That's great! But if I'm not mistaken, the component can't update itself because nothing is reactive.

**Comment by Maronato** [comment]
There is no way currently but it seems like a nice feature indeed.

**Comment by Maronato** [comment]
Done. To be released in 0.4.0, which should be out later today.

**Comment by Maronato** [comment]
0.4.0 released

**Comment by trevorgehman** [comment]
Awesome, I just looked at the PR and it's fantastic! This is turning into a fantastic notification library.

The whole pattern of using components to build custom notifications is really great. I don't see other notification libraries doing this. This allows me to build unique notifications for different scenarios beyond simple success/error/info notices.

I wonder what you think about this @Maronato : Let's say we want to notify users when a background process has started, what its progress is, and when it's finished. So visually we have:

<img width="336" alt="Screen Shot 2019-11-05 at 5 03 40 PM" src="https://user-images.githubusercontent.com/3209864/68250146-49627780-ffee-11e9-8678-9732465b90c6.png">

Ideally I would build this notification in a component:

```
BackgroundTaskComponent.vue

<template>
<div class="flex">
{{ text }}
<div class="loader"></div>
</div>
</template>

<script>
export default {
  props: {
    percentComplete: {
      type: Number,
      default: 0,
    },
  },
  created() {
    // Listen to event bus or something to update
  },
  computed: {
    text() {
      return this.percentComplete === 0 ? 'Task is starting' : 'Task is ' + this.percentComplete + '% done.';
    }
  }
}
</script>
```

Then I would control updating it from with my Vuex store or root app, where I store the `toastIds` I need to track.  Is there something like a `createOrUpdate(toastId...)` with this update?

**Comment by Maronato** [comment]
Hey @trevorgehman! v0.5.0 is out and it implements `createOrUpdate` with a third parameter passed to `update`. Please give it a try!
