### ISSUE TITLE
v-on with no argument warning when using toast with custom component

### ISSUE THREAD

**Issue by tobias-wiese** [Maronato/vue-toastification#140]
We use the toasts globally as shown in #134 with Vue3 and encounter a "problem" when using the creating a toast with a custom component.
I create the toast with 
```
import ReportBugComponent from "..."
const toast = useToast();
toast.error(markRaw(ReportBugComponent));
```
(the markRaw was necessary for clearing another vue warning ``` Vue received a Component which was made a reactive object.```)
Now when triggering the toast, the console shows the warning ```v-on with no argument expects an object value. ``` (see screenshot below). This happens even if using an empty vue component.

How can I avoid this?

Screenshot:
![grafik](https://user-images.githubusercontent.com/63233799/97187405-b1cbdb00-17a2-11eb-98fb-fd310cf8a398.png)

**Comment by Maronato** [comment]
Hello, @tobias-wiese!

Thank you for reporting this.

To avoid it, you must provide an empty object as the `listeners` parameter of the custom component:

```ts
import ReportBugComponent from "..."
const toast = useToast();
toast.error({
  component: markRaw(ReportBugComponent),
  listeners: {}
});
```

That said, both your need to add `markRaw` and to define default `listeners` are bugs that should be fixed by #141.

**Comment by Maronato** [comment]
[v2.0.0-beta.7](https://github.com/Maronato/vue-toastification/releases/tag/v2.0.0-beta.7) has been released with a fix. Please give it a try and reopen the issue if the problem persists.

**Comment by tobias-wiese** [comment]
@Maronato now it's working perfectly fine, thank you!
