### ISSUE TITLE
CDN引入如何使用？

### ISSUE THREAD

**Issue by wangpeng1478** [Maronato/vue-toastification#145]

**Comment by Maronato** [comment]
I think what you wanted to ask is how to use this package with a CDN?

If that's it, you should be able to use jsdelivr 

https://www.jsdelivr.com/package/npm/vue-toastification

**Comment by Maronato** [comment]
Here is an example:
https://jsfiddle.net/afc6Lo2x/

**Comment by Maronato** [comment]
Feel free to reopen the issue if that is not what you meant :)
