### ISSUE TITLE
Click and scroll

### ISSUE THREAD

**Issue by Juanses** [Maronato/vue-toastification#158]
## Versions

- 2.0

## Describe the bug
The page scrolls to the top every time that a toast is called.

## Expected behavior
Instead of scrolling the page, the toast should show wherever the position on the page would be.

## Steps to reproduce
- I have many components on the page
- When I click on a button component, the pages scrolls to the top of the page and shows the toast
- [Video of the problem](https://www.loom.com/share/79288941a9014a44bdad02318256d033)

## Your Environment
 - Device: Desktop
 - OS: MacOS
 - Browser : Chrome 
 - Version : latest version

**Comment by Maronato** [comment]
Hello! Thanks for reporting this :)

Unfortunately, I wasn't able to reproduce your issue. If I had to guess, you are using a `<a href="#" />` or a similar tag to deploy your toast, and that's what is causing the issue.

Below is a Codesandbox demo showing that when deployed using a button, it does not navigate to the top of the page, but it does when deployed from an anchor (`a`) tag:

[![Edit romantic-agnesi-itkyw](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-agnesi-itkyw?fontsize=14&hidenavigation=1&theme=dark)

![CleanShot 2021-01-02 at 21 21 13](https://user-images.githubusercontent.com/19658460/103469201-81736080-4d40-11eb-96f3-dd3be9af2c05.gif)

Closing this as not reproducible.
