### ISSUE TITLE
Failed to resolve component: RouterLink

### ISSUE THREAD

**Issue by EngHell** [Maronato/vue-toastification#162]
## Versions

- 2.0

## Describe the bug

When providing a template containing router-link the component fails to solve with the next message:
```js
[Vue warn]: Failed to resolve component: RouterLink 
  at <ToastSuccessAddForm key=1 toast-id=0 resourceId=1  ... > 
  at <VtToast key=0 eventBus= 
Object { allHandlers: {…} }
 position="top-right"  ... > 
  at <TransitionGroup tag="div" enter-active-class="Vue-Toastification__bounce-enter-active" move-class="Vue-Toastification__bounce-move"  ... > 
  at <VtTransition transition="Vue-Toastification__bounce" class="Vue-Toastification__container top-right" > 
  at <VueToastification eventBus= 
Object { allHandlers: {…} }
 >
```

## Expected behavior

What should happen is, that a toast with a router link is created but instead it is not.

## Steps to reproduce

1. Create a component containing router-link, can be with a render function or template both fail for example.
Component.vue
```vue

<script lang="ts">
import { defineComponent, h, resolveComponent } from 'vue'

export default defineComponent({
	props: {
		resource: {
			type: String,
			required: true,
		},
		resourceId: {
			type: Number,
			required: true,
		},
	},
	setup(_) {
		return () =>
			h('div', [
				`${_.resource} was succesfully created. `,
				h(
					resolveComponent('RouterLink'),
					{
						to: {
							name: 'users.update',
							params: { id: _.resourceId },
						},
					},
					() => ['Click here to review'],
				),
			])
	},
})
</script>
```
2. Second use this component as content for Toast.success or any variant.
app.js
```ts
import MyComponent from "./Component.vue"
....
const component = {
				component: MyComponent
			}
toast.success(component, { timeout: false })
```

## Your Environment

-vite: 2.0.0-beta34
-vue:3.0.5(@next)
-vue-router:4.0.3 (@next)

## Additional context
This component renders fine as you can see in the next screen shot at the bottom you can see its complete, (despite the fact theres no underline in the link due to css)
![imagen](https://user-images.githubusercontent.com/5654345/105569756-10edad00-5d0a-11eb-970f-9f1455325273.png)

**Comment by EngHell** [comment]
I have made some reasearch and i belive this is due to the fact that the app.context differs from the main app context when you call createApp or if youre using render, check this repo for a working fix https://github.com/pearofducks/mount-vue-component/blob/master/index.js

**Comment by Maronato** [comment]
Hello! I may be too late, but this will probably help someone else.

Your findings are correct. When you register the `Toast` plugin, an entirely new app is created to prevent the plugin from messing with things in your actual app.
That, however, results in the context between both apps being different, and, therefore, your global plugins and components won't be available within toasts.

While I do like your solution of copying the context over, I don't think it is necessary for sharing the Vue router. All you need to do is to make the toast app `use` the same router instance as your actual app through the `onMounted` hook:
```ts
app.use(router)

const toastOptions = {
  onMounted: (_, toastApp) => {
    // Register the router
    toastApp.use(router);
  },
};
app.use(Toast, toastOptions);
```
Here is a [working example](https://stackblitz.com/edit/vue-toastification-vue-router?file=src/main.ts):

![CleanShot 2021-10-17 at 19 35 44](https://user-images.githubusercontent.com/19658460/137647387-473bd6f9-fafd-4380-b8f1-040e8f5e1b25.gif)

**Comment by tiagoskaneta** [comment]
@Maronato while that works for Vue router, what would be your suggestion for other arbitrary plugins?

I have, for example, a dependency to Quasar (https://quasar.dev/) and duplicating the `use` plugin registration, although possible, is not ideal. In particular for multiple dependencies, this can quickly become too convoluted.

Ideally it should be possible to just reuse the existing app, although I'm not entirely familiar with what ways could this plugin mess it up.

**Comment by Maronato** [comment]
To reuse the existing app, the plugin would, besides other things, need to replace the root component with something like 
```html
<Fragment>
  {{ old root }}
  {{ toast root }}
</Fragment>
```

While that might work, it may break things in difficult-to-track ways because plugins and your app may make assumptions about the shape of the component tree.

Instead of reusing the app instance, you can reference the data that plugins/etc inject into your regular app onto the toast app. Third-party and user content can be stored in mostly two places: `app._context` and `app.config`. Using the `onMounted` hook you can copy over the properties that you need, or you can merge them by reference, so that both share the same state. Keep in mind that, as they share state, changes can come from both ways.

By default, Vue-toastification will not interact with the app's context or configs, but you should still keep that in mind in case you face any weird bugs.

Here is an example of setup that should cover 99% of use cases. Any plugins, components, mixins, directives, provides and global properties you set in your regular app will be available inside toasts:
```ts
const toastOptions: PluginOptions = {
  onMounted: (_, toastApp) => {
    /* Merge or replace the context properties you need */
    toastApp._context.components = app._context.components
    toastApp._context.directives = app._context.directives
    toastApp._context.mixins = app._context.mixins
    toastApp._context.provides = app._context.provides
    toastApp.config.globalProperties = app.config.globalProperties
  },
};
```

[Here](https://stackblitz.com/edit/vue-toastification-vue-router-tzahja?file=src/main.ts) is a working example showing the sharing of not only `RouterLink` but also reactive values provided through other plugins:
![CleanShot 2021-10-18 at 13 54 59](https://user-images.githubusercontent.com/19658460/137775527-42799399-b12c-4547-b6aa-eb151cca2e5c.gif)

**Comment by Maronato** [comment]
With that said, I'm not familiar with Quasar but it seems to be a lot more than a "plugin".
Even so, most if not all possible places to store data in an `app` are easily available and mergeable using the method displayed above.

If it doesn't work for you, however, please report back so we can look for alternatives

**Comment by Maronato** [comment]
The feature seemed useful and simple to implement, so I went and did it. Now all you need is to provide `shareAppContext: true` when registering the plugin.

**Comment by RaiVaibhav** [comment]
Hi Team,

Tried sharing the context across on vue 2 app, but it's not working, does it focus only on the vue 3?
Currently not able to use the services if I use the custom component inside the custom toast component.
```
  <div class="t-container">
      <Button
        v-if="changeTimeForAllQuestionsBtn.isVisible"
        type="link"
        size="sm"
        :fullHeight="true"
        :title="changeTimeForAllQuestionsBtn.isDone ? `${'Done'}!` : 'Change for all question'"
        :loading="changeTimeForAllQuestionsBtn.isLoading"
        @click="applyTimingToAllQuestions"
      />
  </div>
  ```

**Comment by mrleblanc101** [comment]
How would one do this in Nuxt ?
Options are defined in `nuxt.config.js` which doesn't have access to `app`.
Or would it be possible to backport `shareAppContext` to v1 of the plugin for Vue 2 / Nuxt 2 ?

**Comment by EmmanuelJego** [comment]
For those using Vue 2, here how I managed to be able to use `RouterLink` within a toast:

- import my component for the toast content
`import MyComponent from "path/to/myComponent ";`
- set the router property for my component
`MyComponent.router = this.$router;`
- launch a toast with my component
```
this.$toast(
  MyComponent,
  {
    ...options
  }
);
```
- now, within `MyComponent`, I am able to use `<router-link>` tags successfully 👍

**Comment by brickgale** [comment]
tried `shareAppContext: true` but ended up with some errors (something to do with esm bundler), i opted for the mounted part for vue-router on the toast options.

**Comment by nathanchase** [comment]
For anyone that is trying to use `vue-toastification` with Nuxt 3, this is what worked for me:

```js
// /plugins/vue-toastification.client.js

import Toast from 'vue-toastification/dist/index.mjs';
import { defineNuxtPlugin, useRouter } from '#app';
import 'vue-toastification/dist/index.css';

export default defineNuxtPlugin(nuxtApp => {
  const toastOptions = {
    onMounted: (_, toastApp) => {
      toastApp.use(useRouter());
    },
  };

  nuxtApp.vueApp.use(Toast, toastOptions);
});
```
```js
<script setup lang="ts">
import { useToast } from 'vue-toastification';
import CustomNotification from '@/components/CustomNotification.vue';
import 'vue-toastification/dist/index.css';

toast(CustomNotification);
</script>
```
