### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by MichaelWerner** [Maronato/vue-toastification#168]
Hello,

maybe I'm just doing something wrong, but somehow I can't get it to work.
I did npm install --save vue-toastification

In my nuxt.config.js I have

  /*
   ** Nuxt.js modules
   */
  modules: [
    '@nuxtjs/axios',
    ["vue-toastification/nuxt", {
      timeout: false,
      draggable: false,
      position: 'bottom-center',
      hideProgressBar: true,
      icon: false
    }]
  ],

and in my index.vue I have

,
  created() {
    this.$toast(
      'I am a toast'
    )
  },

The toast is shown but none of the options are used. So the toast is in the top right corner, has a progress bar, has an icon, and disappears after some time.

 The only way I can use the options is writing them in created()...

Another thing is, I can see the toast only when I do
npm run dev

When I build it for production
npm run build

the toast is a message at the bottom of the page.

Any ideas what is going wrong?

Thanks,

Michael

**Comment by simonbuehler** [comment]
i have the same issue - `npm run pod` doesn't work as the (s)css or js is not correct, dev is ok

**Comment by simonbuehler** [comment]
@MichaelWerner see https://github.com/Maronato/vue-toastification/issues/155#issuecomment-759658007 for your other issue

**Comment by simonbuehler** [comment]
ok, purgecss dropped some needed styles, in laravel mix 
`purgeCss({safelist: [/^Vue-Toastification/, /^top-/, /^bottom-/]}).`  fixed it

**Comment by MichaelWerner** [comment]
> ok, purgecss dropped some needed styles, in laravel mix
> `purgeCss({safelist: [/^Vue-Toastification/, /^top-/, /^bottom-/]}).` fixed it

Thank you. I will keep that in mind should I need it in the future. I was running out of time so I used a different toast plugin.
