### ISSUE TITLE
Color option

### ISSUE THREAD

**Issue by hessel-bb** [Maronato/vue-toastification#171]
so i was trying to add tailwind css classes to my toast notification. But i could not really get this working. 
Can't you like the timer etc. add an option for bg-colors and text-colors? 

its easier to apply colors this way instead of just writing new css. I think its a great feature :)

**Comment by bradley-varol** [comment]
This is documented and I've successfully themed this package using Tailwind like so:

First you need to add some custom classes (creates a high specifty in CSS which increased priority and overrides the default styles):
```js
Vue.use(Toast, {
    toastClassName: 'custom',
    bodyClassName: ['custom'],
});
```

Now you can override the default styles in your project CSS/SASS etc. Here's my CSS for example:
```css
/* The notification itself */
.Vue-Toastification__toast.custom {
    @apply min-w-0 px-6 py-3 border-2 shadow-none select-none rounded-xl bg-dark;
}

/* The icon which i'm replacing with a component vue-material-icons (more on how to do this in the docs) /*
.Vue-Toastification__toast.custom .Vue-Toastification__icon {
    @apply h-auto;
}

/* Success variant of the notification */
.Vue-Toastification__toast--success.custom {
    @apply border-success text-success;
}

/* etc */
.Vue-Toastification__toast--error.custom {
    @apply border-danger text-danger;
}

/* The content - use this to override the default font styling etc */
.Vue-Toastification__toast-body.custom {
    @apply self-center font-sans text-base font-bold leading-relaxed;
}
```

Hope this helps 😃
