### ISSUE TITLE
rtl toast alignment is not working properly

### ISSUE THREAD

**Issue by mo3auya91** [Maronato/vue-toastification#179]
## Versions
Relese version: 1.7.11
Vue version: 2.5.17
## Describe the bug

I tried to create the toast, It works and the toast shows up. but I have a problem with rtl support.
here is my config:
```
const toastOptions = {
    position: "bottom-left",
    timeout: 5000,
    closeOnClick: true,
    pauseOnFocusLoss: true,
    pauseOnHover: true,
    draggable: true,
    draggablePercent: 0.6,
    showCloseButtonOnHover: false,
    hideProgressBar: false,
    closeButton: "button",
    icon: true,
    rtl: false
}
```
this will get me a toast like this on mackbook pro 15.4"
<img width="1421" alt="Screenshot 2021-03-23 at 20 57 08" src="https://user-images.githubusercontent.com/6853643/112204537-754ebf00-8c1c-11eb-9d79-e0ef16e36f2b.png">
and its perfect, but I noticed this is not how it shows at **15.60-inch (1366x768)** screens

![WhatsApp Image 2021-03-23 at 21 45 47](https://user-images.githubusercontent.com/6853643/112208760-63234f80-8c21-11eb-8b31-97026b1b372e.jpeg)

this how it look on macbook 15 inch on your demo page
please notice the red arrows at `position`, `rtl layout` and the `toast position`

<img width="1440" alt="Screenshot 2021-03-23 at 20 50 58" src="https://user-images.githubusercontent.com/6853643/112205015-06259a80-8c1d-11eb-9246-0f78f689507d.png">
<img width="1429" alt="Screenshot 2021-03-23 at 20 52 35" src="https://user-images.githubusercontent.com/6853643/112205020-06be3100-8c1d-11eb-8245-432dd2dbae3a.png">

**Comment by alirezajokar** [comment]
i have same issues in rtl mode in any position.
this problem happen when use firefox. in chrome that work fine.

**Comment by alirezajokar** [comment]
@Maronato

**Comment by mo3auya91** [comment]
@Maronato 
Thanks for the fix, does it merged to the latest release? If not, when will it be merged?
As I noticed the last update on the latest relase was 2 days ago.

**Comment by Maronato** [comment]
I haven't released it as there are a couple more bugs I want to fix and include in the next release. It will be released by the end of the day, though

**Comment by ymgsmz** [comment]
@Maronato Facing the same issue on Chrome now, you may add the same changes as what you did https://github.com/Maronato/vue-toastification/commit/e82c89b182b1f16b6a9ad81818242ffe5707a0f1 for `webkit` ?!
I managed to fix it temporarily

**Comment by ahmed-fawzy99** [comment]
I'm on chrome and I too have this bug as exactly show by the OP. I have a multilanguage app and the toasts work fine on English locale, but things get missy when I switch to RTL.
