### ISSUE TITLE
Conditionally globally disable the plugin when registering

### ISSUE THREAD

**Issue by bradley-varol** [Maronato/vue-toastification#182]
Thanks for this awesome package with such great documentation and so many features.

I'd like to completely disable notifications on mobile. I'm currently using the [nuxt device module](https://github.com/nuxt-community/device-module) which allows determining the user agent via a javascript variable. Ideally i'd be able to do something like this in my nuxt plugin:

```js
import Vue from 'vue';
import Toast from 'vue-toastification';

Vue.use(Toast);

export default ({ $device }) => {
    Toast.enabled = $device.isDesktop;
};

```

Is this something that is currently possible? Right now I believe I'd have to use `this.$device.isDesktop && this.$toast()` all over my application which isn't ideal.

Thanks again.

**Comment by mgsmus** [comment]
I don't know Nuxt and I'm new to Vue but I'm using vue-toastification like this:

_plugins/toast.js:_
```
import {useToast} from "vue-toastification";

export default {
    install: (app, options) => {
        app.config.globalProperties.$toast = useToast()
    }
}
```

and I'm using globally like this:

```
methods:{
    doSomething() {
        this.$toast.success('Success!')
    }
}
```

Maybe you can do something inside plugins/toast.js, like returning a fake empty interface instead of useToast() if the device is not desktop. Just an idea...

(I don't even know if that's a valid code, just sayin)
```
export default ({ $device }) => {
    install: (app, options) => {

        const enabled = $device.isDesktop;

        app.config.globalProperties.$toast = enabled ? useToast() : {
            success(content, options) {
                // null
            }
        }
    }
}
```

**Comment by bradley-varol** [comment]
Nice idea! I haven't tried it as I just went with conditionally calling the toast method around my app. I'm moving from Vue to React at the moment so this issue can be closed if desired.
