### ISSUE TITLE
Vue module not found. Electron nuxt production build.

### ISSUE THREAD

**Issue by knight-dev** [Maronato/vue-toastification#186]
Hi. I'm having an issue with the library when running in production. It works fine on the dev build. Any assistance is greatly appreciated. Please see error log below:

Uncaught Error: Cannot find module 'vue'
Require stack:
- C:\Users\User\source\repos\electron\appname\build\win-unpacked\resources\app.asar\node_modules\vue-toastification\dist\cjs\index.js
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:887)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:33)
    at Module._load (internal/modules/cjs/loader.js:732)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at Object.<anonymous> (C:\Users\User\source…dist\cjs\index.js:5)
    at Object.<anonymous> (C:\Users\User\source…t\cjs\index.js:1545)
    at Module._compile (internal/modules/cjs/loader.js:1078)

Config:
modules: [
    "@nuxtjs/vuetify",
    "@nuxtjs/axios",
    "@nuxtjs/auth-next",
    "@nuxtjs/style-resources",
    "vue-toastification/nuxt"
  ],

I also tried as a plugin but got strangely got a syntax error, unexpected '.'

package.json
"devDependencies": {
    "@mdi/font": "5.9.55",
    "@nuxtjs/vuetify": "1.11.3",
    "@vue/test-utils": "1.1.3",
    "@xpda-dev/core": "^0.1.6",
    "@xpda-dev/electron-builder": "^0.2.1",
    "@xpda-dev/electron-launcher": "^0.3.0",
    "@xpda-dev/webpack-step": "^0.1.2",
    "ava": "2.4.0",
    "babel-plugin-webpack-alias-7": "0.1.1",
    "browser-env": "3.3.0",
    "cross-env": "7.0.3",
    "deepmerge": "4.2.2",
    "electron": "12.0.2",
    "electron-builder": "22.10.5",
    "electron-devtools-installer": "3.1.1",
    "native-ext-loader": "2.3.0",
    "node-sass": "4.14.1",
    "nuxt": "2.15.3",
    "require-extension-hooks": "0.3.3",
    "require-extension-hooks-babel": "1.0.0",
    "require-extension-hooks-vue": "0.4.2",
    "roboto-fontface": "0.10.0",
    "sass-loader": "10.0.2",
    "vuetify": "2.4.8",
    "webpack": "4.44.2",
    "webpack-node-externals": "2.5.2"
  },
  "dependencies": {
    "@nuxtjs/auth-next": "^5.0.0-1607693598.34d83ea",
    "@nuxtjs/axios": "^5.12.3",
    "@nuxtjs/style-resources": "^1.0.0",
    "apexcharts": "^3.22.2",
    "electron-cgi": "^1.0.6",
    "file-saver": "^2.0.5",
    "ip": "^1.1.5",
    "luxon": "^1.25.0",
    "vue-apexcharts": "^1.6.0",
    "vue-toastification": "^1.7.11"
  }

**Comment by victororlyk** [comment]
I have simillar issue, and the problem here is that I haven't found a way to use this library with vue 2 which uses composition api. so I don't know how to access it in setup

**Comment by knight-dev** [comment]
> I have simillar issue, and the problem here is that I haven't found a way to use this library with vue 2 which uses composition api. so I don't know how to access it in setup

Thank you for your feedback
