### ISSUE TITLE
Perhaps the wrong type Element in the props code.

### ISSUE THREAD

**Issue by iliyaZelenko** [Maronato/vue-toastification#2]
Nice package! I have a little question. It became interesting for me to look at the code, I came across this line of code. 

https://github.com/Maronato/vue-toastification/blob/2da26a4588c2276b5d6d2379e72f81e2e358ff76/src/components/ToastContainer.vue#L84

Is there such a type in Vue for props? I can not find this in the documentation. Are you sure this is not a mistake?

**Comment by Maronato** [comment]
Hello! That's not a vue type, it is actually a native HTML [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element).

**Comment by iliyaZelenko** [comment]
Ok, I didn’t know that we can specify global objects in the likeness of Element and I can not find in the documentation where this is mentioned. Interesting.

**Comment by Maronato** [comment]
Right over [here](https://vuejs.org/v2/guide/components-props.html#Type-Checks) it says:
> In addition, type can also be a custom constructor function and the assertion will be made with an instanceof check.

**Comment by iliyaZelenko** [comment]
Yes, why am I so not attentive? 😄 Thanks for the quote, now I will know this with confidence.
