### ISSUE TITLE
Centered toast position or customizable toast positions

### ISSUE THREAD

**Issue by dfun90** [Maronato/vue-toastification#250]
## Detailed Description
As of right now there are a handful of positions a toast can use to define where on the screen it gets displayed.  
Those position values are hardcoded as an `enum` inside the `constants.ts` file as following:
```ts
export enum POSITION {
	TOP_LEFT = "top-left",
	TOP_CENTER = "top-center",
	TOP_RIGHT = "top-right",
	BOTTOM_LEFT = "bottom-left",
	BOTTOM_CENTER = "bottom-center",
	BOTTOM_RIGHT = "bottom-right"
}
```
In the code are checks if the specified position is a valid item of the `enum POSITION`, this makes it rather hard to e.g. define your own CSS classes to use for positioning. I've tried to just simply just pass a custom string matching the class for the position when creating a toast, but the toast just stops working completely if doing so.  

## Context
In certain situations the preset positions are not completely viable for a proper situation.  
**Example:** _In our app a user clicks a button to revoke usage rights to some section for another user which they have to confirm via a confirmation toast. 
❓ --> Having the toast show somewhere on the side of the screen is often misleading or users don't necessarily see them and are confused. 
✔ --> Having a toast pop up directly in the center of the screen is clear and precise and doesn't leave any questions open that there is something the user has to do._  

## Possible Implementation
A possible way to implement this could be by specifying the custom position names and css classes when you initialize the toast plugin.

**Comment by Maronato** [comment]
Hello!
> In our app a user clicks a button to revoke usage rights to some section for another user which they have to confirm via a confirmation toast.

You shouldn't use a toast for that. Toasts(aka [Snackbars](https://material.io/components/snackbars#usage)) have a [well-defined design purpose](https://uxdesign.cc/toasts-or-snack-bars-design-organic-system-notifications-1236f2883023). Quote:
> [...] the key design principle is that they do not interrupt users from performing primary tasks.

Perhaps what you need is a [dialog box](https://material.io/components/dialogs). Also, you consider reading [Toast versus Dialog boxes: which to use when?](https://stackoverflow.com/questions/2809531/toast-versus-dialog-boxes-which-to-use-when)

**Comment by dfun90** [comment]
> Hello!
> 
> > In our app a user clicks a button to revoke usage rights to some section for another user which they have to confirm via a confirmation toast.
> 
> You shouldn't use a toast for that. Toasts(aka [Snackbars](https://material.io/components/snackbars#usage)) have a [well-defined design purpose](https://uxdesign.cc/toasts-or-snack-bars-design-organic-system-notifications-1236f2883023). Quote:
> 
> > [...] the key design principle is that they do not interrupt users from performing primary tasks.
> 
> Perhaps what you need is a [dialog box](https://material.io/components/dialogs). Also, you consider reading [Toast versus Dialog boxes: which to use when?](https://stackoverflow.com/questions/2809531/toast-versus-dialog-boxes-which-to-use-when)

Hey!  

What you are saying is probably right, but that doesn't really solve the beginning topic of this issue.  
What this issue was about originally was a way to customize the positioning of the toasts itself, instead of having a few possibilities hard-coded into the code.  

So you might consider re-opening the issue for this exact issue, thanks. :)
