### ISSUE TITLE
The toggle button of Hide progress bar is not align with the data shown in Preview the code

### ISSUE THREAD

**Issue by mark-ng** [Maronato/vue-toastification#251]
## Describe the bug
The toggle button of Hide progress bar is not align with the data shown in Preview the code

## Expected behavior

When the toggle button is green, the hideProgressBar option in Preview the code section should be true, and vice versa.

## Steps to reproduce

Steps:
1. Visit https://maronato.github.io/vue-toastification/
2. Immediately can see the toggle button of Hide progress bar is not align with the data shown in Preview the code

**Comment by Maronato** [comment]
Nice catch! Thanks :)
