### ISSUE TITLE
Add support for Vue router

### ISSUE THREAD

**Issue by justmedev** [Maronato/vue-toastification#261]
At the moment, when creating a toast and then switching route, the toast disappears instantly.

## Detailed Description
Add support for Vue router. When changing page the toast shouldn't instantly disappear. It should stay

## Context
When making a login page for example, I would like to show a toast 'Logged in' while redirecting to the requested page.

## Possible Implementation
Put it over the router view component somehow

**Comment by Maronato** [comment]
Hello! Sorry about the delay and about the pesky stale bot.
Can you provide some code to reproduce your issue? For me it works fine. Below is a sandbox that shows it working:
https://stackblitz.com/edit/vue-router-test-r3rqp1?file=index.js
![CleanShot 2021-10-17 at 17 12 36](https://user-images.githubusercontent.com/19658460/137643384-7582b843-9a95-40cf-bb7e-2d5c061e5df9.gif)

**Comment by Maronato** [comment]
Could you provide a minimum repo that reproduces the issue?

**Comment by justmedev** [comment]
Sorry for my unclear reply. For some reason it magically started working. I probably just thought it wasn't working :)

Sorry for any inconveniences I may have caused.
