### ISSUE TITLE
Hide from vue-devtools instances list

### ISSUE THREAD

**Issue by ivanq3w** [Maronato/vue-toastification#271]
"vue-toastification" Vue instance is always first and selected, and we need to change to default App 1 to inspect.
How can we hide it or may be set second in this list?
![image](https://user-images.githubusercontent.com/58051684/134313846-141d9f20-4876-4fc9-8f58-0da86be1029c.png)

**Comment by Maronato** [comment]
Hello!
The order depends on the order of app initialization.
Anyhow, I will hide the app from devtools. There is no real reason to keep it.

**Comment by Maronato** [comment]
Done! The change will be added to the next release

**Comment by Maronato** [comment]
I think it's the same thing, yes. Any app created with `createApp` will be displayed in the devtools

**Comment by eserdinyo** [comment]
Hey @Maronato , Is it possible to apply the same fix also to the V1?
