### ISSUE TITLE
Sass compilation error in 1.7.14 

### ISSUE THREAD

**Issue by OwenPattison** [Maronato/vue-toastification#296]
## Versions

1.7.14

## Describe the bug

When I import the "~vue-toastification/src/scss/index" compilation fails with the following error

SassError: Invalid CSS after "...in-left: -(math": expected expression (e.g. 1px, bold), was ".div($vt-toast-max-"
        on line 63 of node_modules/vue-toastification/src/scss/_toastContainer.scss
        from line 4 of node_modules/vue-toastification/src/scss/index.scss

## Expected behavior

The sass should compile

## Steps to reproduce

Steps:
1. Include ~vue-toastification/src/scss/index
2. try to compile 

## Your Environment

- Node 14.17.6
- Webpack 5.51.1
- mini-css-extract-plugin 2.2.2

**Comment by Abdulqudus001** [comment]
Had the same issue. Had to bump up my sass to `^1.33.0` and sass-loader to `^12.3.0`

**Comment by Maronato** [comment]
@Abdulqudus001 is correct. You have to update sass

**Comment by OwenPattison** [comment]
Thanks for this @Abdulqudus001.

Just to clarify for the benefit of others; I was using `node-sass 6.0.0` and this still failed after upgrading sass-loader to `^12.3.0`
I moved from `node-sass` (now deprecated) to `dart-sass` and that has resolved the issue.
