### ISSUE TITLE
HTML Toast Support

### ISSUE THREAD

**Issue by palmtown** [Maronato/vue-toastification#315]
## Detailed Description

Enable the ability to pass HTML as the toast content.  Note that I am using Vue 3.

## Context

I would like to include a link in the toast that the user can click.

## Possible Implementation

Change {{ content }} to  v-html="content" in VtToast.vue ?

**Comment by Maronato** [comment]
Hello @palmtown! 

What you want is possible with a custom component. See #248 for an example.

Addressing your proposed implementation, `v-html` is a dangerous directive, much more so when used in a third party library where end users should not care about implementation details. See #306 for a discussion that explains the issue in detail.
