### ISSUE TITLE
The Icon conflicts with IDE (PHPStrom/WebStorm)

### ISSUE THREAD

**Issue by iliyaZelenko** [Maronato/vue-toastification#32]
**Version**
0.2.0

In PHPStrom and WebStorm your component `Icon` in conflict with my component `Icon` in my project. 
I mean, I am prompted to import your `Icon`, instead of mine.

![image](https://user-images.githubusercontent.com/13103045/76083907-594b9180-5fb7-11ea-8c88-179d5d76fb36.png)

This is a pretty nasty problem for me and my team. You could just rename the component, please.

**Comment by Maronato** [comment]
This is pretty odd. Vue toastification components are not exposed and are not registered as global.

I can change the names but I also want to know if there is a way to fix it without doing that, as that would be a breaking change.

I don't use webstorm, so I'm not familiar with this behavior. VSCode does not suggest to autoimport third party's internal components, only the ones exported by the main file.

Do you know if:
- the Icon component is the only one that causes that?
- other plug-ins/library's internal components suffer from this as well?
- there is a way to "hide" components from webstorm's autoimport or suggestions?

**Comment by iliyaZelenko** [comment]
Yes, that too seemed strange to me.

> the Icon component is the only one that causes that?

**Comment by Maronato** [comment]
I was unable to reproduce the bug but that may be my fault for not setting up webstorm properly. Can you try and see if it also happens on the latest version?

Nevertheless, I'm writing the 1.0 release which will rename all components to a better, scoped `VtComponent` naming scheme to avoid further problems.

**Comment by iliyaZelenko** [comment]
> Can you try and see if it also happens on the latest version?
I have the latest version: `2019.3.3`

> Nevertheless, I'm writing the 1.0 release which will rename all components to a better, scoped VtComponent naming scheme to avoid further problems.

Wonderful i will update when it comes out.

**Comment by Maronato** [comment]
The latest version of vue-toastification (now 0.9.0)

**Comment by Maronato** [comment]
@iliyaZelenko v1.0.0 is out and should fix the issue, among other things. Please give it a try and report back if you find any issues. Here is the [changelog](https://github.com/Maronato/vue-toastification/releases/tag/v1.0.0)
