### ISSUE TITLE
Use variables to toggle the toast state

### ISSUE THREAD

**Issue by blackawn** [Maronato/vue-toastification#323]
## Detailed Description

Is it possible to define the state of the toast by myself?
For example, I want the state of the toast corresponding to the request. Reduce some judgment sentences
## Context

```js
requestMethod().then((res) => {
  if (res.code === 200){
    toast.success(res.data.message, {
      timeout: 1500
    });
  }
  if (res.code === 201){
    toast.error(res.data.message, {
      timeout: 1500
    });
  }
  if (res.code === 203){
    toast.info(res.data.message, {
      timeout: 1500
    });
})
```
## Possible Implementation

```js
requestMethod().then((res) => {
  /*
  res: {
    code: 200 | 201 | 202,
    data: {...}
    toast: {
      status: success | info | waring | error ...
      msg: ...
    }
  }
  */
  toast(res.toast.status ,res.toast.msg, {
    timeout: 1500
  });
})
```

**Comment by Soviut** [comment]
For posterity, you could call it like this.

```javascript
toast[res.toast.status](res.toast.msg, { timeout: 1500 })
```

However, the options object already contains a `type` value

```javascript
toast(res.toast.msg, {
  type: res.toast.status,
  timeout: 1500
})
```

Though I would not recommend passing explicit toast data in your API responses. That couples things incredibly tightly to your web frontend. It'd be much saner to make a function that returns the appropriate status/type based on the http response code.

```javascript
function codeToStatus(code) {
  if (code === 200) {
    return 'success'
  } else if (code >= 400 && code <= 499) {
    return 'error'
  }
}

toast(res.data.msg, {
  type: codeToStatus(res.code),
  timeout: 1500
})
```

**Comment by blackawn** [comment]
> 对于后代，你可以这样称呼它。
> 
> ```js
> toast[res.toast.status](res.toast.msg, { timeout: 1500 })
> ```
> 
> 但是，选项对象已包含一个值`type`
> 
> ```js
> toast(res.toast.msg, {
>   type: res.toast.status,
>   timeout: 1500
> })
> ```
> 
> 尽管我不建议在 API 响应中传递显式 Toast 数据。这将事情与你的网络前端紧密地结合在一起。根据 http 响应代码创建一个返回适当状态/类型的函数会更合理。
> 
> ```js
> function codeToStatus(code) {
>   if (code === 200) {
>     return 'success'
>   } else if (code >= 400 && code <= 499) {
>     return 'error'
>   }
> }
> 
> toast(res.data.msg, {
>   type: codeToStatus(res.code),
>   timeout: 1500
> })
> ```

Thanks for your answers and suggestions
