### ISSUE TITLE
Type error with Vue 2.7

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#339]
## Versions

- 1.0

## Describe the bug

`Generic type 'CombinedVueInstance' requires 6 type argument(s).`

![Screenshot 2022-07-19 at 23 02 18](https://user-images.githubusercontent.com/153197/179848640-7e1e88de-337a-4c4f-9d73-fef89695bf88.png)

## Expected behavior

No type error

## Steps to reproduce

Steps:
1. Use in a project that has Vue 2.7 in dependencies
2. Type check the project

## Your Environment

 - Device: -
 - OS: macos
 - Browser -
 - Version -

## Additional context

`CombinedVueInstance` has additional argument `SetupBindings` in its type:

```
export type CombinedVueInstance<
  Instance extends Vue,
  Data,
  Methods,
  Computed,
  Props,
  SetupBindings
> = Data &
  Methods &
  Computed &
  Props &
  Instance &
  (SetupBindings extends void ? {} : SetupBindings)
```

I believe that `CombinedVueInstance` is considered internal by Vue so ideally it wouldn't be referenced directly.

**Comment by Swedish-li** [comment]
Maybe you need update vue to  v2.7.10
https://github.com/vuejs/vue/pull/12727

**Comment by rchl** [comment]
Cool, thanks for pointing that out.
This was not the case at the time of creating this issue. :)
