### ISSUE TITLE
Can't use i18n translation in custom component

### ISSUE THREAD

**Issue by polyminthe** [Maronato/vue-toastification#350]
## Versions

- 1.7.14

## Describe the bug
Property "$t" was accessed during render but is not defined on instance

## Expected behavior
I wish i can use i18n inside the component

## Steps to reproduce

Steps:
1. Install normally
2. Set up plugin
3. Create a component
4. use i18n inside the component =>  <span>{{ $t('valueNameToTranslate') }}</span>
5. Use toast.update to create or update a existing toast component =>
 ```
toast.update(
    numeroLotIC,
    {
      content: {
        component: ToastEpnUploadProgress,
....
```

## Your Environment
 - Device: Laptop
 - OS: Windows 11
 - Browser : Edge
 - Version : 106.0.1370.47

**Comment by polyminthe** [comment]
I found the solution.
Just need add :`  shareAppContext: true, 
`on `.use(Toast,...`
and everything work well.

**Comment by ttibau** [comment]
I'm still receiving the same error. 

I'm using `shareAppContext:true`  on my main.js use. 

I'm using `1.7.14` version

Somebody fixed that?

**Comment by prochorz** [comment]
It seems like there might be an issue stemming from different versions of internationalization (i18n), as well as the challenge of initializing a new Vue instance within a plugin. Here's my proposed solution:
```js
app.use(toast,
    {
        onMounted: (_, baseApp) => {
            baseApp.use(i18n);
        }
     }
);
```
