### ISSUE TITLE
Bug with custom component (Type Script)

### ISSUE THREAD

**Issue by iliyaZelenko** [Maronato/vue-toastification#4]
[This functionality](https://github.com/Maronato/vue-toastification#using-a-custom-component) does not work for TypeScript components. TypeScript components (classes) have `typeof === 'function'`, and I looked at your code, [the object is being checked](https://github.com/Maronato/vue-toastification/blob/master/src/js/utils.js#L34), this is the problem. I don’t have time for reproduction, this bug already took my 30 minutes.

Error:
```typescript
import { Component, Vue } from 'vue-property-decorator'

@Component
export default class ToastContentRender extends Vue { // typeof === 'function'
  // code
}
```

Works:

```js
export default { // typeof === 'object'
  // code
}
```

**Comment by Maronato** [comment]
Hey @iliyaZelenko!
I'm sorry this issue is happening. Do you know if `component instanceof Vue` would work with typescript to validate the vue component?
If not, what would be a suitable way to fix the issue? I've never used typescript in a Vue app like this :/

**Comment by iliyaZelenko** [comment]
> Do you know if component instanceof Vue would work with typescript to validate the vue component?

Despite the fact that it is indicated [here](https://stackoverflow.com/a/42624969/5286034) that this should work, the working approach seems to be in the TypeScript: `component.prototype instanceof Vue`. [Here](https://codesandbox.io/s/nuxtnuxtjs-typescript-t63mx) is a demo confirming this.

**Comment by Maronato** [comment]
I've added both just in case. The new release is out with the fixes. Could you give it a try?

**Comment by Maronato** [comment]
I'll be closing the issue due to inactivity, but feel free to ask me to reopen if the issue persists.
