### ISSUE TITLE
Newlines in a toastr

### ISSUE THREAD

**Issue by Cannonb4ll** [Maronato/vue-toastification#66]
Hi!

I have been using this with great pleasure, hats of for this great awesome toastification package. Rarely I see any good toasters 🎉

That being said, I might of missed it, but I seem to be unable to render newlines in a toast, is this supported?

**Comment by Maronato** [comment]
Hello! I'm happy to hear that you like it :)

You are correct. By default, whitespace is treated using the [browser's default](https://www.w3schools.com/cssref/pr_text_white-space.asp) `normal` value. This means that sequences of whitespace will collapse into a single whitespace, throwing away newlines.

Rendering newlines is indeed a good "feature" to have, so I'll add it to the next release :)

While it's not out, you may fix it by adding this CSS rule to the toast body using the `toastClassName` option:
```css
white-space: pre-wrap;
```

Here is a working example:
[![Edit amazing-ellis-ozbij](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-ellis-ozbij?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Cannonb4ll** [comment]
Thank you for the temporary bypass! 👏

**Comment by Maronato** [comment]
Finally released on 1.5.0

**Comment by Cannonb4ll** [comment]
Awesome! 🤩
