### ISSUE TITLE
Cannot find namespace 'JSX'.

### ISSUE THREAD

**Issue by Armaldio** [Maronato/vue-toastification#67]
## Versions

- 1.4.0

## Describe the bug

The compiling step show warning

## Expected behavior

When compiling, the app should not throw warnings about this

## Steps to reproduce

Steps:
1. Install normally
2. Set up plugin for nuxt (with typescript)

## Your Environment

 - Device: Computer
 - OS: W10
 - Browser Brave
 - Version 1.5.123

![image](https://user-images.githubusercontent.com/3089715/78874833-49f3b400-7a4d-11ea-86e4-ee7296610e6f.png)

**Comment by Maronato** [comment]
Hello! I'm sorry I took so long to answer :/ Rough times. 

You probably need to add a shim for TSX and JSX. Just add a file named `shims-tsx.d.ts` to the root of your project (or to the same folder as your `vue-shim.d.ts`) with the following content:

```ts
import Vue, { VNode } from "vue";

declare global {
  namespace JSX {
    interface Element extends VNode {}
    interface ElementClass extends Vue {}
    interface IntrinsicElements {
      [elem: string]: any;
    }
  }
}
```

If you need an example, refer to the one on [the examples folder](https://github.com/Maronato/vue-toastification/blob/master/examples/nuxt-typescript/types/shims-tsx.d.ts).

If it does not solve your problem, please let me know so I can reopen the issue :)

**Comment by Armaldio** [comment]
Yeah saw that in example after
Thanks 👍
