### ISSUE TITLE
NuxtModuleOptions not exported

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#68]
The `NuxtModuleOptions` interface is not exported in:
https://github.com/Maronato/vue-toastification/blob/59290cb05bd2ed41674a6e943e52edba4b25a6ff/nuxt/index.d.ts#L1-L2

I'd like it to be exported so that I can annotate module options in nuxt.config.js (NOT using TS) like so:
```js
    ['vue-toastification/nuxt', /** @type {import('vue-toastification/nuxt').NuxtModuleOptions} */({
        containerClassName: 'my-container-class',
        position: 'top-left',
    })],
```

**Comment by rchl** [comment]
Can workaround with `/** @type {import('vue-toastification/src/types').NuxtModuleOptions} */` (or maybe it's the way to go?).

**Comment by Maronato** [comment]
Hello! Sorry for the late response.
`NuxtModuleOptions` is not exported by `vue-toastification/nuxt/index.d.ts` because it is not defined there.

As you figured out, the proper way to reference it would indeed be through
`vue-toastification/src/types`
