### ISSUE TITLE
Invalid documentation/types regarding Nuxt module options

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#69]
## Versions
- 1.4.0

## Describe the bug
As far as the documentation and TS types go, both `cssFile` and plugin options have to be specified in the same, flat object like so:
```js
    ['vue-toastification/nuxt', {
        cssFile: 'ssss.css',
        containerClassName: 'my-container-class',
        position: 'top-left',
    })],
```

But as far as the actual code goes, the user has to pass the plugin options through `pluginOptions` like so:
```js
    ['vue-toastification/nuxt', {
        cssFile: 'ssss.css',
        pluginOptions: {
            containerClassName: 'my-container-class',
            position: 'top-left',
        },
    })],
```
## Expected behavior
Code, documentation and types should match.

## Steps to reproduce
1. Register Nuxt module, per documentation, with:
```js
    ['vue-toastification/nuxt', {
        position: 'top-left',
    })],
```
2. Notice that setting doesn't apply (notification uses default top-right placement).

**Comment by Maronato** [comment]
Oof that's pretty serious. Will push a fix right now

**Comment by Maronato** [comment]
Fixed on 1.4.1

**Comment by connecteev** [comment]
@Maronato thanks for this fix with nuxt, love your repo and how well-maintained it is!

**Comment by rchl** [comment]
I agree, the code and documentation quality is excellent and the level of customization that is allowed is almost infinite :)
Thank you.
