### ISSUE TITLE
this.$toast.clear() don't dismiss instantly

### ISSUE THREAD

**Issue by psdon** [Maronato/vue-toastification#7]
When I execute `this.$toast.clear()`, it takes about 2 seconds before notification was closed.

**Comment by Maronato** [comment]
Hello @psdon! I just tried it out and couldn't reproduce the problem. Please note that when you clear the toasts, they will still execute their leaving transition and won't simply disappear.

Please give the fiddle below a try and tell me if your results are the same
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-6vsos?fontsize=14)

**Comment by psdon** [comment]
This was related to issue #6 where transition bounce don't work. Closing this issue now.
