### ISSUE TITLE
Problem with toast size during transition when using custom layout

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#82]
## Versions
1.7.0

## Describe the bug
With my custom layout for toasts, the size of the toast changes during fade-out animation, causing an ugly looking jump.

## Expected behavior
Size of the toast not changing during hiding animation.

## Steps to reproduce
Reproduction [demo](https://codesandbox.io/s/vue-toastification-padding-4o9yx?file=/pages/index.vue).

1. Click the button to show a notification.
2. Click the close button and notice that the width of the toast increases (jumps) when fade-out animation starts.

![width-change-bug](https://user-images.githubusercontent.com/153197/81322588-83433200-9094-11ea-806f-15cccb9feec7.gif)

## Additional context
You can see the main changes (style overrides) in index.vue file.
I've also overridden animation style as it's easier to see the problem when toast position doesn't change during animation.

This problem boils down to __toast having a 100% width which is interpreted differently when `setAbsolutePosition` function in `VtTransition.vue` changes position of the toast to `absolute` on leave animation.

I believe the correct fix for this issue is to "freeze" width of the toast in https://github.com/Maronato/vue-toastification/blob/995625f25933121301aef34d498c6aacd62c0952/src/components/VtTransition.vue#L60-L64
So add a line:
```js
el.style.width = el.offsetWidth + 'px';
```

**Comment by Maronato** [comment]
Thanks for the report and nice solution!
