### ISSUE TITLE
Issue with SPA page and not always existent container

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#86]
## Detailed Description
This is related to #70 which did not really solve my issue.

**Scenario**: SPA application where we want to use custom `container` but that container doesn't exist on every page.
If the user initially opens a page that doesn't include the container, then toasts won't work even after the user navigates to page that has the container. That's because vue-toastification initializes on loading of first page.

**Scenario**: SPA application where the container changes (is recreated) on every navigation.
In that case, toasts will only work on the initial page. After navigating the container will no longer be in the DOM.

## Context
I'd like toasts to work on pages that include the container and they can silently fail on pages that don't.

## Possible Implementation
On my side (Nuxt application), I could update toast defaults on each navigation but it's extra logic that I would hope I can avoid.
On the vue-toastification side, maybe it could re-evaluate `container` function on every toast opening? That would change existing behavior though.

**Comment by rchl** [comment]
My solution, for now, is to call `$toast.updateDefaults(toastDefaults)` from `mounted()` hook of the page component that contains the container.
I can live with that if you decide that this shouldn't be addressed.

**Comment by Maronato** [comment]
Evaluating the container on every toast created can be expensive and unnecessary (or even a breaking change) for most cases.

The [`filterBeforeCreate`](https://github.com/Maronato/vue-toastification#filterbeforecreate) hook is called for every toast created and may work for your use case.

The implementation would look something like:
```js
Vue.use(Toast, {
  filterBeforeCreate: (toast) => {
    Vue.$toast.updateDefaults({ container: containerCallback});
    return toast;
  }
}
```

If that does not work for you I can consider adding it to the next major release.

**Comment by rchl** [comment]
Thank you. I think one of those two solutions will work for me. Currently using mine.
