### ISSUE TITLE
Toast dimension might change slightly before transitioning out

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#87]
## Versions
- 1.7.1

## Describe the bug
On closing the toast, the content within the toast might jump around during the hide transition, causing unwanted jumpiness.

Before closing:
![Screenshot 2020-05-26 at 13 18 12](https://user-images.githubusercontent.com/153197/82894778-6abb8e80-9f53-11ea-95f8-644e5b53de04.png)

During closing:
![Screenshot 2020-05-26 at 13 18 22](https://user-images.githubusercontent.com/153197/82894786-6e4f1580-9f53-11ea-87fb-c6a0857870d0.png)

## Expected behavior
No change in dimensions during hiding.

## Steps to reproduce
The bug is very dependant on the content of the popup, font sizes, browser, and some other factors as it's due to precision loss when using `offsetWidth` so it's not easy to create a case that reproduces reliably. 

EDIT: This should reproduce: https://codesandbox.io/s/amazing-cherry-wx8n6?file=/src/App.vue

## Your Environment
 - OS: macOS
 - Browser Chrome 83

## Additional context
The issue is due to using `element.style.width = element.offsetWidth + 'px'` to "freeze" the width before starting the hide transition. That can cause the size of the toast to change slightly, causing the content to move around.

This is because at least Chrome doesn't support sub-pixel precision for `offsetWidth` property so we get values rounded to the full integer that loose some precision. (relevant bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=360889).

A possible way to fix it is to use `element.getBoundingClientRect().width` (supports sub-pixels) instead but that's not exactly equivalent to `element.offsetWidth` as former is affected by transforms while latter not. I'm not sure if there is any other API that could be more relevant here.

**Comment by rchl** [comment]
Actually created TS that should work: https://codesandbox.io/s/amazing-cherry-wx8n6?file=/src/App.vue

**Comment by Maronato** [comment]
I gave it a try and `.getBoundingClientRect()` seems to be the better solution all around. Not being affected by transforms is a con in my opinion since it may break custom transitions that transform the component. 

Also, there does not [seem to exist](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements) any other relevant APIs.

I'll create a PR switching to `.getBoundingClientRect()` and also locking the component's height (for now, only the width is locked).

**Comment by rchl** [comment]
I was just thinking that taking into account transforms could be bad in case toast normally has scaling transform applied.

So if there is`scale(1.1)` applied then I think dimensions will grow by 10% every time bounding client width is used to update `style.width`.

I can't verify it right now but I think that is what would happen.

Personally, the fix using getBoundingClientRect will work for me, but it could be a problem for some, I fear.

**Comment by Maronato** [comment]
[`window.getComputedStyle()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) seems to check all boxes. (supports subpixel precision and returns non transformed values)

**Comment by rchl** [comment]
Oh, the good old `getComputedStyle`. Forgot about it.
I thought it wouldn't work for values like `width: auto` or `width: 50%` but it actually does.

**Comment by Maronato** [comment]
Fix released on [1.7.6](https://github.com/Maronato/vue-toastification/releases/tag/v1.7.6). Please give it a try and report back any issues you find :)

**Comment by rchl** [comment]
It does fix my issue. Thank you.
