### ISSUE TITLE
TouchEvent is not defined

### ISSUE THREAD

**Issue by zuneFX** [Maronato/vue-toastification#88]
## Versions

- 1.7.1

## Describe the bug

When trying to dismiss a toast on click, the console shows an "Uncaught ReferenceError: TouchEvent is not defined" at "node_modules\vue-toastification\dist\esm\index.js".

## Expected behavior

The toast should dismiss correctly on click and with the corresponding animation.

## Your Environment

 - OS: W10 & Linux
 - Browser: Firefox 76.0.1

**Comment by Maronato** [comment]
Turns out most desktop browsers do not implement touch events. Crazy!

Thanks a lot for the report! I'm working on it right now and should release a fix in the next few minutes.

**Comment by Maronato** [comment]
Fixed on 1.7.2. Please give it a try and report back if the issue persists :)

**Comment by zuneFX** [comment]
Sure thing, though it seems like it's all good now, thank you!
