### ISSUE TITLE
Vuex Support?

### ISSUE THREAD

**Issue by uncle-scooter** [Maronato/vue-toastification#9]
Getting issues when using in a Vuex action. 
`_this2.$toast is not a function`

I'm guessing the package isn't being passed to Vuex somehow. Or perhaps I'm missing something. 

Any ideas?

**Comment by Maronato** [comment]
You can't use `this.$toast` directly because `this` inside Vuex is not the vue instance.

There are 2 ways to use it inside vuex:
```js
this._vm.$toast
```
And 
```js
import Vue from "vue";

Vue.$toast
// or
Vue.prototype.$toast
```
